version: '3'

services:

  postgres:
     image: 'postgres:alpine'
     env_file:
       - '.env'
     volumes:
       - 'postgres:/var/lib/postgresql/data'
     ports:
       - '5432:5432'


  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:5000
        --access-logfile -
        --reload
        "project.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/project'
    ports:
      - '5000:5000'
    depends_on:
      - postgres



volumes:
  postgres:
