version: '3'

services:
  redis:
    image: 'redis:5.0-alpine'
    command: redis-server --requirepass devpassword      #默认没有密码，这里开启，密码必须和settings里的对应
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:5000
        --access-logfile -
        --reload
        "project.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/project'
    ports:
      - '5000:5000'


  postgres:
    image: 'postgres:alpine'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  celery:
    build: .
    command: celery worker -l info -A project.blueprints.user.celery_task    #-l 可设置为info, debug,more, -A 传入包含task的那个文件
    env_file:
      - '.env'
    volumes:
      - '.:/project'

volumes:
  redis:
  postgres:
