version: '3'

services:
  client:
    build: ./client
    volumes:
      - './client:/usr/app'
    ports:
      - '5000:5000'
    environment:
      - REDIS_HOST:redis
      - REDIS_PORT:6379
  api:
    build: ./Api
    volumes:
      - './Api:/usr/app'
    ports:
      - '4000:4000'
  redis:
    image: "redis:latest"
    ports:
      - '6379:6379'
  mongo:
    image: "mongo:3.6"
