version: '3'

services:
    web:
       build: .
       ports:
              - "5000:5000"
       depends_on:
           - db
       volumes:
        - '.:/usr/myapp'

    db:
       build: ./db
  
              


